export const DEMO_PRODUCTS = [
  {
    title: 'Organic Tomatoes',
    description: 'The tomatoes on this stall are not grown six hundred miles away and kept in cool storage. They are picked before the sun hits the glasshouse and they arrive on your doorstep the same morning. That is the difference you cannot fake in a photograph, and it is the difference you will taste in the first slice.\n\nEvery tray is a single variety, chosen because it ripens on the vine instead of being gassed to colour. The result is a fruit that smells like summer when you lift the lid: a faint sweetness over a proper tatty tomato leaf. Heirloom strains ripen at slightly different speeds, so you will find fruits at more than one stage of redness in the same tray. That is not a defect. That is the point.\n\nThe tomatoes are grown two kilometres from the pack shed using drip irrigation and compost made from the farm\'s own straw. No broadacre spraying, no blanket fertiliser. Each plant is walked and hand-checked every other day during the season.\n\nUse them raw in a bowl with sea salt and torn basil within a day of delivery, or roast a few wedges with olive oil and garlic for a side that takes ten minutes. They keep best at room temperature, stem side down, never in the fridge. 1 kg',
    price: 25000,
    imageUrl: 'https://dummyimage.com/400x300/3E6B4F/FBF8F1&text=Tomatoes',
    category: 'vegetables',
    wholesale: 1,
  },
  {
    title: 'Fresh Strawberries',
    description: 'The strawberry season in this valley is short, and that is exactly why they are worth buying now. Grown in raised soil beds rather than hydroponic trays, the berries are pollinated by bees that live on the farm. Each one is cut by hand with a short snips, leaving the green calyx attached so the berry holds its juice. They are picked on cool mornings and packed into shallow crates within an hour.\n\nThe variety this season is a mid-season day-neutral that keeps fruiting from spring to the first frost. It has the highest sugar reading we have recorded on the brix scale all year. Eat them that evening for the best sweetness and texture.\n\nFor resellers and bakeries the wholesale option is available in 250 g crates, cut the same morning and packed to your spec. 250 g',
    price: 50000,
    imageUrl: 'https://dummyimage.com/400x300/3E6B4F/FBF8F1&text=Strawberries',
    category: 'fruits',
    wholesale: 1,
  },
  {
    title: 'Premium Rice',
    description: 'The rice is milled from the whole kernel, which is why a 5 kg sack of it cooks into far more than five kilos of finished meal. We do not polish off the outer layers for the sake of a whiter grain. It is grown on small family plots in the volcanic soils around the north coast district, where the day-and-night range does the final magic on the crop.\n\nBring it to the boil, then lower the heat and cover for twelve minutes. Let it rest, covered and off the heat, for five minutes more before you fork it open. If you skip the rest it releases starch and goes clumpy. Each grain separates and the pot is dry underneath.\n\nThis is a whole family bag rather than a single dinner portion, and it keeps in a sealed container for a full year in a cool, dark pantry. Buy it once and use it slowly. 5 kg',
    price: 15000,
    imageUrl: 'https://dummyimage.com/400x300/3E6B4F/FBF8F1&text=Rice',
    category: 'grains',
    wholesale: 0,
  },
  {
    title: 'Fresh Milk',
    description: 'The milk on the shelf at the back is delivered whole, the same morning it was drawn, and it is not homogenised. The herd is a small group of Jersey cows, picked because their milk carries more cream and flavour than the higher-yielding black and white breeds. The cows are milked once in the quiet of the early morning by the same two people who muck the yard and feed the calves.\n\nThe milk comes to us twice a week, cooled, and is lightly pasteurised to keep it safe for children and the elderly, and bottled the same day it arrives. It stands up to heating, frothing for coffee, and baking far better than shelf-stable UHT cartons.\n\nA carton lasts most households three to four days. Bring a jug or a clean bottle if you want the crate-style refills. 1 L',
    price: 18000,
    imageUrl: 'https://dummyimage.com/400x300/3E6B4F/FBF8F1&text=Milk',
    category: 'dairy',
    wholesale: 0,
  },
  {
    title: 'Grass-Fed Eggs',
    description: 'These are the eggs laid before seven in the morning by hens that actually go outside. They live in a mobile ark that is moved across the pasture every few days, so the insects, clover, and grubs they find in the soil are a genuine part of their diet. That is what produces a yolk so rich and orange it looks artificial, except it is not.\n\nThe farmer cracks one open before packing the tray and weighs it against a light for size. The shells are left whole and brushed, not sprayed, because the natural cuticle on the egg is what keeps bacteria out. The pack size is a tray of twelve.\n\nTo test freshness at home, drop the egg in a glass of water: if it floats, it is near its end; if it sinks and lies flat, it is that morning\'s. For baking, these yolks give cakes and doughs a richness that the paler eggs simply cannot match. 12 pcs',
    price: 22000,
    imageUrl: 'https://dummyimage.com/400x300/3E6B4F/FBF8F1&text=Eggs',
    category: 'dairy',
    wholesale: 1,
  },
  {
    title: 'Green Spinach',
    description: 'Baby spinach is a fussy crop that rewards patience and timing. Each one is cut, bunch by bunch, with a sharp blade when the leaf is small, round and dark enough. The growers pull the whole rosette on a cool morning, not a machine stripping a long row at the hottest part of the afternoon. The leaves you get are no bigger than the palm of your hand because that is when the flavour is sweetest.\n\nThe bed is hoed by hand between rows so the delicate root stays intact all the way from the garden to the crate. These baby spinach leaves cook in a fraction of the time other greens need, wilting down to less than a quarter of their bought volume.\n\nOne bunch is 200 g, and two bunches is a generous serving for a family of four when it wilts. We pick to order, and the crate is tied with twine. 200 g',
    price: 12000,
    imageUrl: 'https://dummyimage.com/400x300/3E6B4F/FBF8F1&text=Spinach',
    category: 'vegetables',
    wholesale: 0,
  },
  {
    title: 'Banana Bunch',
    description: 'This is a cooking banana, and the difference from a dessert banana is written through the whole fruit. These plantains are allowed to hang on the plant until the skins take on a warm, dappled yellow and the flesh begins to sweeten. The stall sells them in the two-to-three day window when they are neither green nor over-the-knob brown.\n\nEvery hand is inspected before it is crated, because a single split or black tip ruins the impression for a buyer. The bunch you get will be 1 kg, which is usually four to six hands, enough for a family for two or three days.\n\nKeep them on the counter in a fruit bowl. The green hands fry beautifully with salt and serve with eggs for a breakfast staple, and the yellow ones are sweet and soft enough to eat alone. 1 kg',
    price: 15000,
    imageUrl: 'https://dummyimage.com/400x300/3E6B4F/FBF8F1&text=Bananas',
    category: 'fruits',
    wholesale: 1,
  },
  {
    title: 'Organic Fertilizer',
    description: 'Compost is not a single product, and the bag we sell here is not a generic peat substitute. It is the actual compost heap from the stall\'s own market garden, turned and aerated through the winter months by hand with a fork until the material is dark, crumbly, and smelling of earth rather than rot. The analysis is printed on the side because we have nothing to hide about what is in the bag.\n\nIt is made from straw bedding, legume hulls, and the vegetable trimmings of the stall, layered with green material and cow manure, so the nitrogen-to-carbon balance is right. Use it as a season dressing in spring and autumn on vegetable beds and the flower border.\n\nStore the sack in a dry place and it will keep for years. For the commercial grower, a wholesale pallet rate is available. 10 kg',
    price: 80000,
    imageUrl: 'https://dummyimage.com/400x300/3E6B4F/FBF8F1&text=Fertilizer',
    category: 'supplies',
    wholesale: 1,
  },
];