/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatIndexRouteImport } from './routes/cat/index'
import { Route as CatCategoryIDRouteImport } from './routes/cat/$categoryID'
import { Route as DetCategoryIDProductIDRouteImport } from './routes/det/$categoryID.$productID'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatIndexRoute = CatIndexRouteImport.update({
  id: '/cat/',
  path: '/cat/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatCategoryIDRoute = CatCategoryIDRouteImport.update({
  id: '/cat/$categoryID',
  path: '/cat/$categoryID',
  getParentRoute: () => rootRouteImport,
} as any)
const DetCategoryIDProductIDRoute = DetCategoryIDProductIDRouteImport.update({
  id: '/det/$categoryID/$productID',
  path: '/det/$categoryID/$productID',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cat/$categoryID': typeof CatCategoryIDRoute
  '/cat/': typeof CatIndexRoute
  '/det/$categoryID/$productID': typeof DetCategoryIDProductIDRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cat/$categoryID': typeof CatCategoryIDRoute
  '/cat': typeof CatIndexRoute
  '/det/$categoryID/$productID': typeof DetCategoryIDProductIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cat/$categoryID': typeof CatCategoryIDRoute
  '/cat/': typeof CatIndexRoute
  '/det/$categoryID/$productID': typeof DetCategoryIDProductIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cat/$categoryID' | '/cat/' | '/det/$categoryID/$productID'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cat/$categoryID' | '/cat' | '/det/$categoryID/$productID'
  id:
    | '__root__'
    | '/'
    | '/cat/$categoryID'
    | '/cat/'
    | '/det/$categoryID/$productID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatCategoryIDRoute: typeof CatCategoryIDRoute
  CatIndexRoute: typeof CatIndexRoute
  DetCategoryIDProductIDRoute: typeof DetCategoryIDProductIDRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cat/': {
      id: '/cat/'
      path: '/cat'
      fullPath: '/cat/'
      preLoaderRoute: typeof CatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cat/$categoryID': {
      id: '/cat/$categoryID'
      path: '/cat/$categoryID'
      fullPath: '/cat/$categoryID'
      preLoaderRoute: typeof CatCategoryIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/det/$categoryID/$productID': {
      id: '/det/$categoryID/$productID'
      path: '/det/$categoryID/$productID'
      fullPath: '/det/$categoryID/$productID'
      preLoaderRoute: typeof DetCategoryIDProductIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatCategoryIDRoute: CatCategoryIDRoute,
  CatIndexRoute: CatIndexRoute,
  DetCategoryIDProductIDRoute: DetCategoryIDProductIDRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
