/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as CatCategoryIdRouteImport } from './routes/cat.$categoryId'
import { Route as DetCategoryIdProductIdRouteImport } from './routes/det.$categoryId.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const CatCategoryIdRoute = CatCategoryIdRouteImport.update({
  id: '/cat/$categoryId',
  path: '/cat/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const DetCategoryIdProductIdRoute = DetCategoryIdProductIdRouteImport.update({
  id: '/det/$categoryId/$productId',
  path: '/det/$categoryId/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/cat/$categoryId': typeof CatCategoryIdRoute
  '/det/$categoryId/$productId': typeof DetCategoryIdProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/cat/$categoryId': typeof CatCategoryIdRoute
  '/det/$categoryId/$productId': typeof DetCategoryIdProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/cat/$categoryId': typeof CatCategoryIdRoute
  '/det/$categoryId/$productId': typeof DetCategoryIdProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/category' | '/cat/$categoryId' | '/det/$categoryId/$productId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/category' | '/cat/$categoryId' | '/det/$categoryId/$productId'
  id:
    | '__root__'
    | '/'
    | '/category'
    | '/cat/$categoryId'
    | '/det/$categoryId/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRoute
  CatCategoryIdRoute: typeof CatCategoryIdRoute
  DetCategoryIdProductIdRoute: typeof DetCategoryIdProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cat/$categoryId': {
      id: '/cat/$categoryId'
      path: '/cat/$categoryId'
      fullPath: '/cat/$categoryId'
      preLoaderRoute: typeof CatCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/det/$categoryId/$productId': {
      id: '/det/$categoryId/$productId'
      path: '/det/$categoryId/$productId'
      fullPath: '/det/$categoryId/$productId'
      preLoaderRoute: typeof DetCategoryIdProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRoute,
  CatCategoryIdRoute: CatCategoryIdRoute,
  DetCategoryIdProductIdRoute: DetCategoryIdProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
